insert into LOCATION (id, name, street, city, area_code) values (51, '3 Armistice Lane', '16236 Lindbergh Plaza', 'Cambarus', 'PH');
insert into LOCATION (id, name, street, city, area_code) values (52, '4404 Stephen Avenue', '1 Anhalt Circle', 'Huadian', 'CN');
insert into LOCATION (id, name, street, city, area_code) values (53, '07377 Namekagon Center', '1054 Atwood Drive', 'Porecatu', 'BR');
insert into LOCATION (id, name, street, city, area_code) values (54, '7399 Glendale Avenue', '90 Lotheville Court', 'Ampeleíes', 'GR');
insert into LOCATION (id, name, street, city, area_code) values (55, '32 Forest Run Way', '45777 Northwestern Junction', 'Tawaran', 'ID');
insert into LOCATION (id, name, street, city, area_code) values (56, '201 Briar Crest Lane', '54368 Cottonwood Drive', 'Orguz', 'BA');
insert into LOCATION (id, name, street, city, area_code) values (57, '6 Bunker Hill Plaza', '465 Mendota Drive', 'Moppo', 'KR');
insert into LOCATION (id, name, street, city, area_code) values (58, '719 Lunder Crossing', '9 Fulton Point', 'Pameče', 'SI');
insert into LOCATION (id, name, street, city, area_code) values (59, '60537 Melrose Street', '9 Swallow Court', 'Seraya', 'ID');
insert into LOCATION (id, name, street, city, area_code) values (60, '851 Northview Plaza', '9 Laurel Street', 'Yuzhno-Sukhokumsk', 'RU');
insert into LOCATION (id, name, street, city, area_code) values (61, '035 Artisan Parkway', '2038 Banding Lane', 'Yonghe', 'CN');
insert into LOCATION (id, name, street, city, area_code) values (62, '74 Dovetail Road', '797 Bunker Hill Place', 'Zselickislak', 'HU');
insert into LOCATION (id, name, street, city, area_code) values (63, '78870 Springs Terrace', '41 Harper Center', 'Liulin', 'CN');
insert into LOCATION (id, name, street, city, area_code) values (64, '21191 Lake View Pass', '38 Brickson Park Drive', 'Xihu', 'CN');
insert into LOCATION (id, name, street, city, area_code) values (65, '6368 Golden Leaf Lane', '68 Mayfield Crossing', 'Karoya', 'ID');
insert into LOCATION (id, name, street, city, area_code) values (66, '4013 Little Fleur Alley', '90934 Pepper Wood Avenue', 'Shimiaozi', 'CN');
insert into LOCATION (id, name, street, city, area_code) values (67, '8823 Namekagon Junction', '497 Lakewood Pass', 'Jalalaqsi', 'SO');
insert into LOCATION (id, name, street, city, area_code) values (68, '02 Bartillon Way', '9439 Ridgeway Terrace', 'Rognedino', 'RU');
insert into LOCATION (id, name, street, city, area_code) values (69, '4 Garrison Hill', '42417 West Lane', 'Jaruco', 'CU');
insert into LOCATION (id, name, street, city, area_code) values (70, '23300 Veith Plaza', '0 New Castle Circle', 'Jiuhu', 'CN');
insert into LOCATION (id, name, street, city, area_code) values (71, '2648 Farragut Point', '0 Pepper Wood Center', 'Itapevi', 'BR');
insert into LOCATION (id, name, street, city, area_code) values (72, '42 Bluestem Crossing', '8007 Dapin Road', 'Leer', 'SS');
insert into LOCATION (id, name, street, city, area_code) values (73, '393 Superior Hill', '31985 Cardinal Park', 'Lameiras', 'PT');
insert into LOCATION (id, name, street, city, area_code) values (74, '010 Dottie Drive', '2 Ilene Drive', 'Beidu', 'CN');
insert into LOCATION (id, name, street, city, area_code) values (75, '21 Kipling Park', '78907 Gulseth Alley', 'Arganil', 'PT');
insert into LOCATION (id, name, street, city, area_code) values (76, '05 Monica Way', '239 Clarendon Way', 'Santa Luzia', 'BR');
insert into LOCATION (id, name, street, city, area_code) values (77, '78581 Harper Place', '28 Fordem Terrace', 'Tenjolaya', 'ID');
insert into LOCATION (id, name, street, city, area_code) values (78, '23948 Dakota Circle', '8 Menomonie Pass', 'El Fahs', 'TN');
insert into LOCATION (id, name, street, city, area_code) values (79, '8497 Welch Trail', '4 Laurel Junction', 'Weishanzhuang', 'CN');
insert into LOCATION (id, name, street, city, area_code) values (80, '07158 Barby Point', '8 Hazelcrest Hill', 'Ourinhos', 'BR');
insert into LOCATION (id, name, street, city, area_code) values (81, '88 Bunting Lane', '1 Continental Point', 'Piggs Peak', 'SZ');
insert into LOCATION (id, name, street, city, area_code) values (82, '381 Service Road', '9 Pond Crossing', '’Unābah', 'AF');
insert into LOCATION (id, name, street, city, area_code) values (83, '2 Kipling Terrace', '3093 Schurz Hill', 'Solnechnogorsk', 'RU');
insert into LOCATION (id, name, street, city, area_code) values (84, '13526 Nelson Drive', '09805 Carberry Trail', 'Sant Julià de Lòria', 'AD');
insert into LOCATION (id, name, street, city, area_code) values (85, '87578 Blackbird Court', '60055 Waxwing Street', 'Mekarsari', 'ID');
insert into LOCATION (id, name, street, city, area_code) values (86, '7 Hanover Pass', '13990 Westport Pass', 'Kristianstad', 'SE');
insert into LOCATION (id, name, street, city, area_code) values (87, '2 Basil Park', '312 New Castle Junction', 'Kanginan', 'ID');
insert into LOCATION (id, name, street, city, area_code) values (88, '14 Morning Crossing', '5 Marcy Center', 'El Cortezo', 'PA');
insert into LOCATION (id, name, street, city, area_code) values (89, '53725 Londonderry Park', '361 Melvin Pass', 'Geyuan', 'CN');
insert into LOCATION (id, name, street, city, area_code) values (90, '7 Sheridan Pass', '2519 Thackeray Court', 'Sitularang Landeuh', 'ID');
insert into LOCATION (id, name, street, city, area_code) values (91, '72 Stoughton Court', '95 Huxley Terrace', 'Gołkowice', 'PL');
insert into LOCATION (id, name, street, city, area_code) values (92, '90935 Morrow Street', '2 Division Crossing', 'Cândido Mota', 'BR');
insert into LOCATION (id, name, street, city, area_code) values (93, '8 Manufacturers Pass', '54 Cambridge Lane', 'Fafe', 'PT');
insert into LOCATION (id, name, street, city, area_code) values (94, '5 Gina Avenue', '6 Summer Ridge Place', 'Lajedo', 'BR');
insert into LOCATION (id, name, street, city, area_code) values (95, '40 Spaight Circle', '9781 Katie Junction', 'Espinheira', 'PT');
insert into LOCATION (id, name, street, city, area_code) values (96, '97883 Corry Park', '72093 Cambridge Trail', 'Batutulis', 'ID');
insert into LOCATION (id, name, street, city, area_code) values (97, '1 Brickson Park Terrace', '4017 Graedel Circle', 'Kilimatinde', 'TZ');
insert into LOCATION (id, name, street, city, area_code) values (98, '297 Sunbrook Crossing', '5627 Merchant Point', 'Järfälla', 'SE');
insert into LOCATION (id, name, street, city, area_code) values (99, '6289 Stuart Parkway', '38 Ronald Regan Pass', 'Huntington', 'US');
insert into LOCATION (id, name, street, city, area_code) values (100, '819 Di Loreto Center', '62298 Crescent Oaks Alley', 'Launceston', 'AU');
